### 01. import library

In [1]:
# 라이브러리 호출

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import math
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

df = pd.read_csv('../file/train_add_category.csv')
df = df.drop(['Unnamed: 0','predicted'], axis=1)
df

data = df.drop('Pawpularity', axis=1)
target = df['Pawpularity']

data['category'].replace('dog',0, inplace=True)
data['category'].replace('cat',1, inplace=True)
data.drop('Id', axis=1, inplace=True)

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size = 0.25, random_state=0)

In [9]:
X_train.columns

Index(['Subject Focus', 'Eyes', 'Face', 'Near', 'Action', 'Accessory', 'Group',
       'Collage', 'Human', 'Occlusion', 'Info', 'Blur', 'category'],
      dtype='object')

In [10]:
X_train['Subject Focus']

2838    0
1225    0
7126    0
1701    0
3214    0
       ..
9225    0
4859    0
3264    0
9845    0
2732    0
Name: Subject Focus, Length: 7434, dtype: int64

In [14]:
w_updates1234 = []
for i in X_train.columns:
    w_update123 = np.zeros_like(X_train[i])
    w_updates1234.append(w_update123)
        
w_updates1234

np.zeros((1,1))

array([[0.]])

In [19]:
w1212 = []

for i in X_train.columns:
        w_k1212 = np.zeros((1,1))
        w1212.append(w_k1212)
        
w1212

[array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]])]

### 02. Linear Regression

In [101]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# 선형 회귀 OLS로 학습/예측/평가 수행.
lr = LinearRegression()
lr.fit(X_train, y_train)

y_preds = lr.predict(X_test)
mse = mean_squared_error(y_test, y_preds)
rmse=np.sqrt(mse)

print('RMSE : {0:2f}'.format(rmse))

RMSE : 20.575872


In [103]:
# 교차검증

from sklearn.model_selection import cross_val_score

# cross_val_score()로 5 폴드 세트로 RMSE 구하기
mse_score = cross_val_score(lr, data, target, scoring='neg_mean_squared_error', cv=5)
rmse_score = np.sqrt(-1*mse_score)
avg_rmse = np.mean(rmse_score)

# cross_val_score(scoring='neg_mean_squared_error')로 반환된 값은 모두 음수
print('5 folds 의 개별 RMSE scores : ', np.round(rmse_score, 2))
print('5 folds 의 평균 RMSE : {0:.3f}'.format(avg_rmse))

5 folds 의 개별 RMSE scores :  [20.71 20.85 20.88 20.12 20.42]
5 folds 의 평균 RMSE : 20.597


### 03. Ridge Regression

- Ridge 클래스의 주요 생성 파라미터는 alpha(릿지 회귀의 alpha L2 규제 계수에 해당)

In [104]:
from sklearn.linear_model import Ridge

# alpha = 10으로 설정해 릿리 회귀 수행
ridge = Ridge(alpha=10)
neg_mse_scores = cross_val_score(ridge, data, target, scoring='neg_mean_squared_error', cv=5)
rmse_scores = np.sqrt(-1*neg_mse_scores)
avg_rmse = np.mean(rmse_scores)

print('5 folds 의 개별 RMSE scores : ', np.round(rmse_scores, 2))
print('5 folds 의 평균 RMSE : {0:.3f}'.format(avg_rmse))

5 folds 의 개별 RMSE scores :  [20.71 20.85 20.88 20.12 20.42]
5 folds 의 평균 RMSE : 20.596


- 릿지 회귀는 alpha 값이 커질수록 회귀 계수 값을 작게 만듬

In [106]:
# 릿지에 사용될 alpha 파라미터의 값을 정의
alphas = [0, 0.1, 1, 10, 100]

# alphas list의 값을 반복하면서 alpha에 따른 평균 rmse를 구함
for alpha in alphas:
    ridge = Ridge(alpha = alpha)
    
    # cross_val_score를 이용해 5 폴드의 평균 RMSE를 계산 
    neg_mse_scores = cross_val_score(ridge, data, target, scoring='neg_mean_squared_error', cv=5)
    rmse_scores = np.sqrt(-1*neg_mse_scores)
    avg_rmse = np.mean(rmse_scores)
    print('alpha {0} 일 때 5 folds 의 평균 RMSE : {1:.3f}'.format(alpha, avg_rmse))

alpha 0 일 때 5 folds 의 평균 RMSE : 20.597
alpha 0.1 일 때 5 folds 의 평균 RMSE : 20.597
alpha 1 일 때 5 folds 의 평균 RMSE : 20.597
alpha 10 일 때 5 folds 의 평균 RMSE : 20.596
alpha 100 일 때 5 folds 의 평균 RMSE : 20.592
